# -*- coding: utf-8 -*-
"""NAPSeminarski.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UHDHASxPB8l64OngIKyt6XZXOOe_OUZ6

# **Ekstrakcija informacija iz korisničkih recenzija hotela i analiza zadovoljstva korisnika**

## Tema, predmet i svrha rada

**Tema rada** je ekstrakcija strukturisanih informacija iz nestrukturisanih tekstualnih podataka primenom velikih jezičkih modela (Large Language Models – LLMs), što je u skladu sa temom 4 kao jednom od predloženih tema.

**Predmet rada** je analiza korisničkih recenzija hotela, koje sadrže subjektivne i implicitne informacije o kvalitetu usluge i zadovoljstvu korisnika, a koje nisu direktno dostupne u strukturisanom obliku.

**Svrha rada** je da se ispita u kojoj meri se primenom velikih jezičkih modela mogu automatski izdvojiti relevantne informacije iz tekstualnih recenzija i dopuniti postojeći dataset. Novi dataset se može kasnije koristiti za dalje analize zadovoljstva korisnika.

## Podaci i izvor podataka

U ovom radu koristi se [**Booking.com Hotel Reviews Dataset**](https://www.kaggle.com/datasets/thedevastator/booking-com-hotel-reviews?resource=download), preuzet sa online platforme [**Kaggle**](https://www.kaggle.com/).

Dataset sadrži korisničke recenzije hotela prikupljene sa platforme Booking.com i obuhvata sledeće tipove podataka:
- **tekstualne recenzije korisnika** (`review_text`), koje predstavljaju slobodan tekst bez prethodne obrade,
- **naslov recenzije** (`review_title`),
- **numeričku prosečnu ocenu hotela** (`avg_rating`),
- **naziv hotela** (`hotel_name`),
- **nacionalnost korisnika** (`nationality`),
- **informacije o korisniku koji je ostavio recenziju** (`reviewed_by`),
- **vremenske podatke** o ostavljanju i prikupljanju recenzije (`reviewed_at`, `crawled_at`),
- **broj slika priloženih uz recenziju** (`images`),
- **URL adrese** recenzije i hotela na Booking.com (`url`, `hotel_url`).

Tekstualne recenzije predstavljaju nestrukturisane podatke koji sadrže implicitne informacije o korisničkom iskustvu, dok strukturirani deo dataseta omogućava kvantitativnu analizu i poređenje hotela.

Podaci su preuzeti u izvornom obliku i nisu unapred ručno prilagođavani, čime se obezbeđuju realni uslovi za primenu ekstrakcije informacija pomoću LLM modela.

## Metodologija rada

Metodologija rada zasniva se na primeni **velikih jezičkih modela (LLMs)** za zadatak ekstrakcije informacija iz nestrukturisanog teksta.

Za implementaciju ekstrakcije koristi se **Python okruženje u Jupyter/Colab notebook-u**, uz primenu biblioteka **LangChain** i **LangExtract**, koje omogućavaju definisanje šeme ekstrakcije i dobijanje strukturisanog izlaza u standardizovanom formatu (npr. JSON).

Modeli će se koristiti bez dodatnog treniranja, oslanjajući se na njihove sposobnosti razumevanja prirodnog jezika i kontekstualne interpretacije teksta.

## Precizna definicija šeme za ekstrakciju informacija

Kako bi se odgovorilo na istraživačko pitanje rada,
definisana je precizna struktura informacija koje će biti izdvojene iz tekstualnih recenzija hotela.

LLM model će generisati strukturirani izlaz sa sledećim atributima:

1. **overall_sentiment**  
   Opšti sentiment recenzije (positive, neutral, negative).

2. aspects_sentiment  
   Sentiment po pojedinačnim aspektima usluge:
   - **cleanliness**
   - **location**
   - **staff**
   - **comfort**
   - **facilities**
   - **value_for_money**
   - **wifi**
   - **food**

3. **mentioned_amenities**  
   Lista pomenutih sadržaja (npr. pool, spa, parking, breakfast, gym).

4. **complaints**  
   Eksplicitno navedeni negativni elementi iskustva.

5. **praises**  
   Eksplicitno navedeni pozitivni elementi iskustva.

6. **would_recommend**  
   Indikacija da li bi korisnik preporučio hotel (true/false/unknown).

## Razlog izbora ekstraktovanih atributa

Izabrani atributi omogućavaju:

- poređenje implicitno izraženog sentimenta sa numeričkom ocenom (avg_rating),
- analizu zadovoljstva po pojedinačnim aspektima usluge,
- identifikaciju dominantnih faktora nezadovoljstva,
- kvantifikaciju pozitivnih i negativnih elemenata iskustva,
- konstrukciju mreže korisnika na osnovu sličnosti sentimenta i ocenjivanih hotela.

Na ovaj način, LLM-ekstrahovani atributi postaju ulaz za kvantitativnu, graf i mrežnu analizu.

## Validacija rezultata ekstrakcije

Tačnost LLM-ekstrahovanog sentimenta biće proverena poređenjem sa
numeričkom ocenom hotela (avg_rating), transformisanom u kategorije sentimenta.

Biće analizirano:
- ukupno poklapanje klasifikacija,
- poklapanje po kategorijama (low/mid/high rating),
- slučajevi neslaganja (visok rating + negativan sentiment).

Ova analiza omogućava procenu konzistentnosti implicitnog i eksplicitnog zadovoljstva korisnika.

## Dalje analize proširenog dataseta

Nakon ekstrakcije informacija, dobijeni podaci biće dodati u postojeći dataset i korišćeni za dalje analize.

U radu će se primarno primeniti **mrežna analiza**, pri čemu se recenzije modeluju kao čvorovi u mreži i povezuju na osnovu **sličnosti sentiment profila po aspektima usluge**. Težina veze između korisnika predstavlja kombinaciju zadovoljstva pojedinim aspektima usluge.

Pored mrežne analize, biće sprovedeno i poređenje **implicitno izraženog sentimenta** sa **numeričkim ocenama**.

Ovako urađene analize omogućavaju dublje razumevanje faktora koji utiču na ukupno zadovoljstvo korisnika i jasno pokazuju vrednost ekstrakcije informacija pomoću velikih jezičkih modela.

## Formalna definicija mrežne analize

U mrežnoj analizi:

- Čvorovi predstavljaju pojedinačne recenzije, pri čemu se svaka recenzija tretira kao jedinstven sentiment profil korisnika.
- Ivica između dva čvora postoji ukoliko je kosinusna sličnost njihovih sentiment profila po aspektima usluge veća ili jednaka definisanom pragu (threshold = 0.7), koji predstavlja visoku sličnost u vektorskom prostoru.
- Težina ivice predstavlja vrednost kosinusne sličnosti između dva korisnička profila.

Sentiment profil svakog korisnika predstavljen je vektorom dužine 8, gde svaka komponenta odgovara jednom aspektu usluge (cleanliness, location, staff, comfort, facilities, value_for_money, wifi, food), a vrednosti su mapirane na numerički opseg {-1, 0, 1}.

Iako više recenzija može pripadati istom hotelu, jedinica analize u mreži nije hotel, već pojedinačni sentiment profil korisnika.
Time se modeluju obrasci percepcije kvaliteta usluge, a ne odnosi između hotelskih entiteta.

Samim tim, mreža ne predstavlja socijalne interakcije između korisnika, već mrežu sličnosti percepcije kvaliteta usluge.

Analiziraće se:
- **degree centrality**
- **betweenness centrality**
- **zajednice korisnika sa sličnim obrascima zadovoljstva**

**Degree centrality** meri broj direktnih veza koje jedan sentiment profil (recenzija korisnika) ima sa drugim profilima.

U ovoj mreži, visoka vrednost degree centrality ukazuje na to da korisnik deli sličan obrazac zadovoljstva sa velikim brojem drugih korisnika. Takvi čvorovi predstavljaju **tipične obrasce percepcije kvaliteta usluge** i mogu se interpretirati kao reprezentativni primeri dominantnog sentiment profila u dataset-u.

Drugim rečima, korisnici sa visokom degree centrality imaju sentiment profil koji je u velikoj meri usklađen sa većinom drugih korisnika.

**Betweenness centrality** meri u kojoj meri se neki čvor nalazi na najkraćim putevima između drugih parova čvorova u mreži.

U kontekstu ove analize, visoka vrednost betweenness centrality može ukazivati na recenzije koje povezuju različite zajednice i potencijalno predstavljaju **prelazne** ili **kombinovane obrasce percepcije kvaliteta usluge**.

- **Hibridni sentiment profil** podrazumeva kombinaciju pozitivnih i negativnih ocena po različitim aspektima usluge (npr. pozitivna čistoća i osoblje, ali negativna lokacija ili komfor). Takvi korisnici ne pripadaju isključivo jednoj homogeno pozitivnoj ili negativnoj grupi, već kombinuju elemente različitih obrazaca zadovoljstva.

- **Prelazni sentiment profil** znači da su ovi korisnici dovoljno slični različitim grupama korisnika, te u mrežnoj strukturi imaju ulogu „mosta“ između grupa. Njihovi sentiment profili povezuju grupe sa različitim percepcijama kvaliteta usluge.

Za razliku od degree centrality, koja identifikuje tipične i dominantne obrasce, betweenness centrality ukazuje na čvorove koji doprinose povezivanju mrežne strukture i interakciji između zajednica.

## Interpretacija, mogućnosti unapredjenja i organičenja

Rezultati rada interpretiraju se u kontekstu subjektivne prirode korisničkih recenzija hotela.
Korisnici često implicitno izražavaju zadovoljstvo ili nezadovoljstvo pojedinim aspektima usluge,
što može dovesti do razlika između numeričke ocene (avg_rating) i sentimenta identifikovanog
primenom LLM modela.

Posebna pažnja posvećena je analizi neslaganja između numeričkih ocena i implicitnog sentimenta,
jer takve situacije mogu ukazivati na kompleksnost percepcije kvaliteta usluge
(npr. visoka ocena uz izražene pritužbe na određeni aspekt).

Ograničenja rada uključuju:

- potencijalne greške u ekstrakciji informacija od strane LLM modela,
- subjektivnu i heterogenu prirodu korisničkih recenzija,
- moguće neravnomernu zastupljenost pozitivnih i negativnih ocena,
- ograničenja u obradi velikog broja zapisa usled API restrikcija.

Moguća unapređenja obuhvataju:

- primenu domen-specifičnih modela za analizu turizma i ugostiteljstva,
- korišćenje few-shot primera radi povećanja preciznosti ekstrakcije,
- proširenje mrežne analize na hotele kao čvorove i analizu zajednica hotela,
- primenu naprednih graf metrika radi detaljnijeg modelovanja odnosa između korisnika.

## Importi
"""

!pip uninstall -y \
    langchain \
    langchain-core \
    langchain-community \
    langchain-openai \
    langgraph \
    langgraph-prebuilt \
    langchain-text-splitters \
    langchain-classic \
    langchain-groq \
    >/dev/null 2>&1

!pip install -q -U \
    "pydantic>=2.7,<3" \
    "langchain==0.2.16" \
    "langchain-core==0.2.43" \
    "langchain-community==0.2.16" \
    "langchain-openai==0.1.14" \
    "langchain-groq" \
    "groq"

print("✔ Stabilne verzije instalirane.")

from google.colab import files
from google.colab import drive
from google.colab import userdata

import pandas as pd
import numpy as np
import json, re, os
import time

import matplotlib.pyplot as plt
import seaborn as sns

import math

from sklearn.metrics import accuracy_score, classification_report, balanced_accuracy_score, f1_score
from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.model_selection import train_test_split

import networkx as nx
from networkx.algorithms import community

from pydantic import BaseModel, Field
from typing import List, Optional, Literal

from langchain.prompts import ChatPromptTemplate
from langchain.output_parsers import PydanticOutputParser
from langchain_groq import ChatGroq

print("OK: biblioteke učitane (pydantic v2 + langchain 0.2.x).")

"""Tokom implementacije primećena je neusklađenost verzija između paketa `langchain`, `langchain-core`, `langchain-community` i `pydantic`, što je dovodilo do grešaka pri importovanju modula i parsiranju strukturisanog izlaza.

Kako bi se obezbedila stabilna i konzistentna konfiguracija okruženja, izvršeno je uklanjanje prethodno instaliranih verzija paketa i instalacija kompatibilnih verzija (pydantic v2.x i langchain 0.2.x).

## Ucitavanje dataseta i pretprocesiranje podataka
"""

BASE_PATH = "/content/drive/MyDrive/NAP_projekat"

os.makedirs(BASE_PATH, exist_ok=True)

drive.mount('/content/drive')

file_path = os.path.join(BASE_PATH, "booking_reviews copy.csv")

df = pd.read_csv(file_path)

print("Učitano:", file_path)
print("Shape:", df.shape)
display(df.head())

"""Nakon učitavanja CSV fajla pomoću funkcije `pd.read_csv()`,
podaci su smešteni u pandas DataFrame strukturu,
čime je omogućena dalja tabelarna obrada i analiza.

Prikaz prvih pet redova (`head(5)`) korišćen je radi
provere uspešnosti učitavanja i preliminarnog uvida
u strukturu kolona i tipove podataka.

Dataset sadrži kombinaciju strukturiranih atributa
(npr. numeričke ocene, naziv hotela, nacionalnost korisnika)
i nestrukturiranog tekstualnog polja `review_text`,
koje predstavlja centralni element za primenu LLM ekstrakcije informacija.
"""

df.info()

"""Analizom strukture dataset-a pomoću funkcije `info()`
dobijen je detaljan pregled tipova podataka i prisustva nedostajućih vrednosti.

Dataset sadrži ukupno 26.675 zapisa i 16 kolona,
koje uključuju kombinaciju numeričkih i tekstualnih atributa.

Numeričke kolone (`avg_rating`, `rating`) predstavljaju kvantitativne ocene hotela,
dok kolona `review_text` predstavlja nestrukturirani tekstualni sadržaj.

Uočava se postojanje nedostajućih vrednosti u pojedinim kolonama,
što zahteva dodatno preprocesiranje pre sprovođenja daljih analiza.

Ovaj korak omogućava identifikaciju relevantnih promenljivih
i planiranje narednih faza obrade podataka.
"""

df.isnull().sum()

"""Analizom nedostajućih vrednosti u dataset-u uočava se
da pojedine kolone sadrže određeni broj praznih zapisa.

Najveći broj nedostajućih vrednosti prisutan je u koloni `images`,
što je očekivano, s obzirom da većina korisnika ne prilaže fotografije uz recenziju.

Manji broj nedostajućih vrednosti prisutan je u kolonama
`review_text`, `avg_rating`, `hotel_name`, `nationality`
i drugim meta-podacima.
"""

df = df[[
    "review_text",
    "avg_rating",
    "hotel_name"
]].copy()

df.head()

"""U ovoj fazi izvršena je selekcija ključnih atributa
koji su relevantni za dalju analizu i ekstrakciju informacija.

Zadržane su sledeće kolone:

- `review_text` – tekstualna recenzija korisnika,
- `avg_rating` – numerička ocena hotela,
- `hotel_name` – identifikacija hotela,

Ovim korakom dataset je redukovan na osnovne promenljive
neophodne za analizu sentimenta i konstrukciju mrežnog modela,
čime se uklanjaju suvišni meta-podaci koji nisu od direktnog značaja
za istraživačko pitanje rada.
"""

df = df.dropna(subset=["review_text", "avg_rating", "hotel_name"]).reset_index(drop=True)
df.shape

df.isnull().sum()

"""U ovom koraku uklonjeni su zapisi koji nemaju vrednosti
u kolonama `review_text`, `avg_rating` i `hotel_name`,
budući da su ove promenljive ključne za dalju analizu.

Bez tekstualne recenzije nije moguće sprovesti LLM ekstrakciju,
dok je numerička ocena neophodna za validaciju rezultata sentiment klasifikacije.

Nakon uklanjanja nedostajućih vrednosti,
dataset sadrži 26.386 zapisa i 3 relevantne kolone,
što predstavlja kvalitetnu osnovu za naredne faze preprocesiranja.
"""

df["review_text"] = df["review_text"].astype(str).str.replace(r"\s+", " ", regex=True).str.strip()

df["ReviewLen"] = df["review_text"].apply(len)
df.head()

"""U ovoj fazi izvršeno je osnovno čišćenje tekstualnih podataka.

Uklonjeni su višestruki razmaci i nepotrebni whitespace karakteri,
čime je obezbeđena konzistentnost tekstualnog sadržaja.

Nakon toga kreirana je nova numerička promenljiva `ReviewLen`,
koja predstavlja dužinu recenzije izraženu brojem karaktera.

Ova promenljiva je značajna za identifikaciju
prekratkih i potencijalno neinformativnih recenzija,
koje mogu negativno uticati na kvalitet ekstrakcije informacija.
"""

plt.figure(figsize=(8,5))
sns.histplot(df["ReviewLen"], bins=50, kde=True)
plt.title("Distribucija dužine recenzija")
plt.xlabel("Dužina recenzije (broj karaktera)")
plt.ylabel("Broj recenzija")
plt.show()

"""Prikazana je distribucija dužine korisničkih recenzija,
izražena brojem karaktera.

Distribucija je izrazito desno asimetrična,
što ukazuje na veliki broj kraćih recenzija
i manji broj veoma detaljnih i dugih komentara.

Ovakav obrazac je očekivan kod korisničkih platformi,
gde većina korisnika ostavlja sažete utiske,
dok manji broj pruža opširne opise iskustva.

Ova analiza dodatno opravdava filtriranje najkraćih 10% zapisa,
kako bi se obezbedio kvalitetniji tekstualni materijal
za primenu velikih jezičkih modela i ekstrakciju aspekata usluge.
"""

percentile_10 = df["ReviewLen"].quantile(0.10)

df = df[df["ReviewLen"] > percentile_10].reset_index(drop=True)
df.shape

"""U cilju povećanja kvaliteta analize,
iz dataset-a su uklonjene najkraće recenzije,
odnosno zapisi ispod 10. percentila distribucije dužine teksta.

Ovaj postupak omogućava eliminaciju
potencijalno neinformativnih ili generičkih komentara
koji ne sadrže dovoljno sadržaja za pouzdanu LLM ekstrakciju.

Nakon filtriranja, dataset sadrži 23.716 zapisa,
što predstavlja kvalitetan i informativan skup podataka
za nastavak analize sentimenta i ekstrakcije aspekata.
"""

correlation = df["avg_rating"].corr(df["ReviewLen"])
print("Pearson korelacija:", round(correlation, 4))

plt.figure(figsize=(6,4))
sns.scatterplot(x="ReviewLen", y="avg_rating", data=df, alpha=0.3)
plt.title("Scatter plot: Dužina recenzije vs. Prosečna ocena")
plt.xlabel("Dužina recenzije")
plt.ylabel("Prosečna ocena")
plt.show()

"""Za ispitivanje povezanosti između dužine recenzije (ReviewLen) i dodeljene numeričke ocene (avg_rating) korišćen je Pearson koeficijent korelacije.

Pearsonov koeficijent korelacije meri jačinu i smer linearne veze između dve numeričke varijable.
Njegova vrednost se kreće u intervalu [-1, 1]:

- r ≈ 1 → jaka pozitivna linearna veza  
- r ≈ -1 → jaka negativna linearna veza  
- r ≈ 0 → ne postoji linearna povezanost  

U ovom slučaju dobijena vrednost iznosi:

r ≈ 0.0059

Ova vrednost je veoma bliska nuli, što ukazuje na praktično nepostojeću linearnu vezu između dužine recenzije i dodeljene ocene.

Scatter grafikon dodatno potvrđuje odsustvo jasnog linearnog obrasca – recenzije različitih dužina pojavljuju se uz širok raspon ocena, bez uočljive tendencije rasta ili pada.

Ovaj rezultat sugeriše da kvantitativna karakteristika teksta (dužina recenzije) sama po sebi nije pouzdan indikator zadovoljstva korisnika.

Zbog toga je za dublje razumevanje korisničke percepcije neophodna semantička analiza sadržaja recenzija, što opravdava primenu LLM modela u nastavku rada.
"""

def rating_to_category(r):
    if r >= 8:
        return "positive"
    elif r >= 6:
        return "neutral"
    else:
        return "negative"

df["rating_category"] = df["avg_rating"].apply(rating_to_category)
df["rating_category"].value_counts()

"""U ovoj fazi izvršena je transformacija numeričke ocene (`avg_rating`)
u kategorijalnu promenljivu `rating_category`,
koja predstavlja aproksimaciju sentimenta zasnovanu na oceni hotela.

Primena sledeće podele omogućava poređenje sa LLM-ekstrahovanim sentimentom:

- ocene ≥ 8 → *positive*
- ocene između 6 i 8 → *neutral*
- ocene < 6 → *negative*

Distribucija pokazuje izrazitu neravnomernost klasa,
pri čemu dominantnu kategoriju čine pozitivne recenzije,
dok je broj negativnih recenzija znatno manji.

Ova neravnomernost je očekivana,
s obzirom da korisnici češće ocenjuju hotele visokim ocenama.

Kreirana promenljiva predstavlja referentnu osnovu
za validaciju tačnosti LLM sentiment klasifikacije
u narednim fazama rada.

"""

plt.figure(figsize=(6,4))
sns.countplot(x="rating_category", data=df, order=["positive","neutral","negative"])
plt.title("Distribucija kategorija sentimenta (na osnovu ocene)")
plt.xlabel("Kategorija")
plt.ylabel("Broj recenzija")
plt.show()

"""Grafik prikazuje distribuciju kategorija sentimenta
dobijenih transformacijom numeričke ocene hotela (`avg_rating`).

Uočava se izražena neravnomernost klasa,
pri čemu dominantnu kategoriju čine pozitivne recenzije,
dok je broj negativnih zapisa znatno manji.

Ovakva distribucija je očekivana u kontekstu platformi
na kojima korisnici češće ostavljaju visoke ocene.

Međutim, neravnomerna zastupljenost klasa
može uticati na evaluaciju modela,
zbog čega će u kasnijim fazama rada
pored tačnosti (accuracy) biti razmatrane i
preciznost (precision), odziv (recall) i F1 mera.

"""

top_hotel_names = (
    df["hotel_name"]
    .value_counts()
    .head(10)
    .index
    .tolist()
)

plt.figure(figsize=(10,6))
sns.boxplot(
    data=df[df["hotel_name"].isin(top_hotel_names)],
    x="avg_rating",
    y="hotel_name",
    color="lightgray"
)
sns.stripplot(
    data=df[df["hotel_name"].isin(top_hotel_names)],
    x="avg_rating",
    y="hotel_name",
    color="blue",
    alpha=0.4,
    jitter=True
)

plt.title("Distribucija ocena za top 10 hotela")
plt.xlabel("Ocena")
plt.ylabel("Hotel")

plt.show()

"""Box-plot prikazuje distribuciju korisničkih ocena za deset hotela sa najvećim brojem recenzija u analiziranom skupu podataka.

Može se uočiti da su ocene izrazito koncentrisane u veoma uskom rasponu (približno između 8.0 i 8.9), što rezultira malim interkvartilnim rasponom i vizuelno „zbijenim“ box-plot prikazom za svaki hotel.

Ovakva struktura ukazuje na dominaciju relativno visokih ocena u uzorku, kao i na prisustvo tzv. ceiling efekta, gde se vrednosti grupišu u gornjem delu skale.

Zbog ograničene varijabilnosti numeričkih ocena, sama prosečna ocena ima smanjenu diskriminativnu moć u razlikovanju hotela. Razlike između hotela su male i teško uočljive samo na osnovu agregiranih numeričkih vrednosti.

Ovo dodatno opravdava primenu LLM-bazirane analize sadržaja recenzija i sentimenta po aspektima, kako bi se identifikovale suptilnije razlike u percepciji kvaliteta usluge koje numerička ocena ne otkriva.

## LLM
"""

print("Biblioteke su već instalirane u inicijalnoj konfiguraciji.")

"""U ovom koraku napominjem da su već instalirane biblioteke neophodne za implementaciju LLM pipeline-a zasnovanog na Groq API servisu.

Instalirane biblioteke:

- **groq** – zvanični Groq API klijent koji omogućava direktnu komunikaciju sa Groq servisom i proveru ispravnosti API ključa.
- **langchain-groq** – integracija Groq modela u LangChain framework.
- **langchain** – framework za kreiranje prompt-ova, parsera i kompletne LLM pipeline strukture.

Ova konfiguracija omogućava:
- autentifikaciju putem Groq API ključa,
- povezivanje sa Llama 3 modelom,
- strukturisanu ekstrakciju informacija iz tekstualnih recenzija,
- validaciju i mapiranje odgovora modela u definisanu Pydantic šemu.

"""

key = userdata.get("GROQ_API_KEY")

print("Key loaded:", key is not None)
if key:
    print("Key prefix:", key[:4], "length:", len(key))

os.environ["GROQ_API_KEY"] = key

"""U ovom koraku Groq API ključ se učitava iz Colab Secrets i postavlja kao promenljiva okruženja (GROQ_API_KEY).

Na ovaj način biblioteke automatski prepoznaju ključ i omogućavaju autentifikovanu komunikaciju sa Groq LLM servisom.

"""

Sentiment = Literal["positive", "neutral", "negative", "not_mentioned"]
Recommend = Literal["true", "false", "unknown"]

class AspectSentiment(BaseModel):
    cleanliness: Optional[Sentiment] = Field(default=None, description="Sentiment za čistoću.")
    location: Optional[Sentiment] = Field(default=None, description="Sentiment za lokaciju.")
    staff: Optional[Sentiment] = Field(default=None, description="Sentiment za osoblje.")
    comfort: Optional[Sentiment] = Field(default=None, description="Sentiment za komfor.")
    facilities: Optional[Sentiment] = Field(default=None, description="Sentiment za sadržaje/facilities.")
    value_for_money: Optional[Sentiment] = Field(default=None, description="Sentiment za odnos cene i kvaliteta.")
    wifi: Optional[Sentiment] = Field(default=None, description="Sentiment za WiFi.")
    food: Optional[Sentiment] = Field(default=None, description="Sentiment za hranu/doručak.")

class ReviewExtraction(BaseModel):
    overall_sentiment: Optional[Literal["positive", "neutral", "negative"]] = Field(
        default=None, description="Opšti sentiment recenzije."
    )

    aspects_sentiment: Optional[AspectSentiment] = Field(
        default=None, description="Sentiment po aspektima usluge."
    )

    mentioned_amenities: Optional[List[str]] = Field(
        default=None, description="Lista pomenutih sadržaja (npr. pool, spa, breakfast)."
    )

    complaints: Optional[List[str]] = Field(
        default=None, description="Kratke fraze koje opisuju negativna iskustva."
    )

    praises: Optional[List[str]] = Field(
        default=None, description="Kratke fraze koje opisuju pozitivna iskustva."
    )

    would_recommend: Optional[Recommend] = Field(
        default=None, description="Da li korisnik preporučuje hotel."
    )

"""U okviru LLM dela rada definisana je šema za ekstrakciju informacija korišćenjem strukturiranog izlaza (structured output).

Šema je implementirana u vidu Pydantic modela, čime se precizno definiše očekivani format odgovora LLM-a. Ovakav pristup omogućava:

- konzistentnost generisanih rezultata (isti format za svaku recenziju),
- automatsku validaciju izlaza (lakše uočavanje grešaka i odstupanja),
- jednostavnu integraciju ekstraktovanih informacija u postojeći dataset.

Definisane su dve klase:

1. **AspectSentiment** – model koji opisuje sentiment po pojedinačnim aspektima usluge (čistoća, lokacija, osoblje, komfor, sadržaji, odnos cena/kvalitet, WiFi, hrana).

Sentiment može imati vrednost:

- `positive`
- `neutral`
- `negative`
- `not_mentioned`

2. **ReviewExtraction** – glavni model koji obuhvata:
   - **opšti sentiment recenzije**,
   - **sentiment po aspektima usluge**,
   - listu **pomenutih sadržaja** (npr. pool, spa, breakfast),
   - eksplicitno navedene **pozitivne** i **negativne** elemente iskustva,
   - indikaciju da li korisnik **preporučuje hotel**.

Sva polja u modelu definisana su kao `Optional`, sa podrazumevanom vrednošću `None`.

Ovakav pristup ima važnu metodološku ulogu:

- model nije primoran da generiše vrednost za svaki aspekt,
- smanjuje se rizik od halucinacija,

Na ovaj način Pydantic model funkcioniše kao formalni „ugovor“ između LLM modela i analitičkog pipeline-a.
"""

parser = PydanticOutputParser(pydantic_object=ReviewExtraction)

prompt = ChatPromptTemplate.from_messages(
    [
        ("system", "You are an expert system for extracting structured information from hotel reviews."),
        ("human", """
Extract the following structured information from the hotel review given below:

{format_instructions}

Review:
{review_text}
""")
    ]
)

llm = ChatGroq(
    model="llama-3.1-8b-instant",
    temperature=0
)

"""U ovom koraku implementiran je LLM model korišćenjem **Groq API servisa**, koji omogućava brzo i besplatno izvršavanje velikih jezičkih modela.

Pipeline se sastoji iz sledećih komponenti:

- **PydanticOutputParser** – omogućava validaciju i strukturisanje izlaza modela prema prethodno definisanoj šemi (`ReviewExtraction`).
- **ChatPromptTemplate** – definiše sistemsku ulogu modela i instrukcije za ekstrakciju informacija.
- **ChatGroq model (llama-3.1-8b-instant)** – koristi se za generisanje strukturiranog odgovora.

Temperatura modela postavljena je na 0 kako bi se obezbedila deterministička i konzistentna ekstrakcija informacija, što je posebno važno u istraživačkom kontekstu radi reproduktivnosti rezultata.

Ova konfiguracija predstavlja osnovu za automatizovanu analizu recenzija i ekstrakciju:

- opšteg sentimenta,
- sentimenta po aspektima usluge,
- pomenutih sadržaja,
- pozitivnih i negativnih elemenata iskustva,
- indikacije preporuke hotela.

"""

format_instructions = parser.get_format_instructions()

chain = (
    prompt.partial(format_instructions=format_instructions)
    | llm
    | parser
)

"""U ovom koraku formiran je kompletan tok obrade (pipeline) koji omogućava automatsku ekstrakciju informacija iz recenzije.

Pipeline funkcioniše po principu:

1. **Prompt** dobija tekst recenzije i instrukcije za JSON formatiranje (`format_instructions`).
2. **LLM model (Groq – llama-3.1-8b-instant)** generiše strukturisan odgovor.
3. **Parser (PydanticOutputParser)** validira i mapira odgovor u strukturisan objekat prema šemi `ReviewExtraction`.

Na ovaj način se obezbeđuje da je izlaz:
- struktuiran,
- validiran,
- spreman za direktno dodavanje u dataset.

"""

sample_review = df["review_text"].iloc[0]

result = chain.invoke({"review_text": sample_review})
result

"""Izvršena je provera rada pipeline-a na jednoj recenziji iz dataset-a.

Model je uspešno:

- identifikovao opšti sentiment,
- klasifikovao sentiment po aspektima,
- izdvojio pozitivne i negativne elemente iskustva,
- generisao indikator preporuke hotela.

Dobijeni rezultat je instanca klase `ReviewExtraction`, što potvrđuje da:

- model generiše validan strukturirani izlaz,
- parser uspešno vrši validaciju,
- pipeline funkcioniše ispravno.

Ovim je potvrđena spremnost sistema za obradu celog skupa podataka.

## Batch obrada recenzija pomoću LLM pipeline-a
"""

SEED = 42
SAMPLE_SIZE = 250
TOP_K_HOTELS = 8

hotel_counts = df["hotel_name"].value_counts()
top_hotels = hotel_counts.head(TOP_K_HOTELS).index.tolist()

df_pool = df[df["hotel_name"].isin(top_hotels)].copy()

per_hotel = math.ceil(SAMPLE_SIZE / TOP_K_HOTELS)

df_sample = (
    df_pool.groupby("hotel_name", group_keys=False)
    .apply(lambda g: g.sample(n=min(per_hotel, len(g)), random_state=SEED))
    .sample(n=min(SAMPLE_SIZE, len(df_pool)), random_state=SEED)
    .reset_index(drop=True)
)

df_sample["sample_id"] = df_sample.index.astype(int)

print("Uzorak shape:", df_sample.shape)
print("Broj hotela u uzorku:", df_sample["hotel_name"].nunique())
df_sample.head()

"""U cilju formiranja stabilne osnove za mrežnu analizu, uzorak recenzija nije formiran uzimanjem prvih N zapisa iz dataseta, već primenom kontrolisanog kriterijuma.

1. Identifikovani su hoteli sa najvećim brojem recenzija u dataset-u (top 8 hotela).
2. Iz svakog od odabranih hotela uzet je približno jednak broj recenzija.
3. Ukupan broj recenzija u uzorku ograničen je na 250.

Broj od 8 hotela predstavlja balans između:

- **raznovrsnosti uzorka** – mreža ne modeluje iskustva vezana za samo jedan ili dva hotela,
- **stabilnosti po hotelu** – svaki hotel ima dovoljan broj recenzija da bi se uočili obrasci percepcije kvaliteta,
- **kompleksnosti mreže** – prevelik broj hotela bi smanjio broj recenzija po hotelu i otežao identifikaciju stabilnih obrazaca percepcije,

Sa 250 recenzija i 8 hotela, prosečno se dobija oko 31–32 recenzije po hotelu, što je dovoljno da:

- se identifikuju dominantni sentiment obrasci,
- detektuju hibridni profili,
- omogući smislena konstrukcija mreže sličnosti.

Ovakav izbor omogućava da mreža reflektuje različite obrasce percepcije kvaliteta usluge, a ne specifičnosti jednog pojedinačnog hotela.

Uzorak je generisan korišćenjem fiksnog `random_state` (SEED), čime se obezbeđuje da se pri svakom pokretanju notebook-a dobija identičan skup od 250 recenzija.

Rezultat ove procedure je DataFrame `df_sample` dimenzije (250, 6), koji sadrži:

- tekst recenzije (`review_text`),
- numeričku ocenu (`avg_rating`),
- naziv hotela (`hotel_name`),
- dužina recenzije (`ReviewLen`),
- kategorijska promenljiva (`rating_category`),
- pomoćni identifikator (`sample_id`) za kasnije povezivanje sa LLM rezultatima.

Ovaj uzorak predstavlja ulaz u LLM pipeline i osnovu za dalju mrežnu analizu.
"""

SAMPLE_PATH = os.path.join(BASE_PATH, "df_sample_250Recenzija.csv")
LLM_PATH = os.path.join(BASE_PATH, "llm_results_250recenzija.jsonl")

if not os.path.exists(SAMPLE_PATH):
    df_sample.to_csv(SAMPLE_PATH, index=False)
    print("Sample fajl sačuvan u Drive:", SAMPLE_PATH)
else:
    print("Sample fajl već postoji:", SAMPLE_PATH)

files.download(SAMPLE_PATH)

if os.path.exists(LLM_PATH):
    print("LLM cache fajl postoji:", LLM_PATH)
else:
    print("LLM cache fajl još ne postoji. Biće kreiran nakon LLM obrade.")

"""Formirani uzorak od 250 recenzija čuva se u eksternom fajlu (`df_sample_250Recenzija.csv`).

Cilj ovog koraka je:

- obezbeđivanje stabilnog skupa podataka za dalju analizu,
- omogućavanje ponovljivosti eksperimenta,
- izbegavanje ponovnog generisanja uzorka pri svakom pokretanju notebook-a,
- osiguravanje da se mrežna analiza uvek vrši nad istim podacima.
"""

results = []

if os.path.exists(LLM_PATH):
    print("Nađen fajl sa LLM rezultatima -> učitavam:", LLM_PATH)
    with open(LLM_PATH, "r", encoding="utf-8") as f:
        for line in f:
            results.append(json.loads(line))
else:
    print("Nema cache fajla -> pokrećem LLM obradu za 250 recenzija...")

    for i, row in df_sample.iterrows():
        try:
            review = row["review_text"]
            res = chain.invoke({"review_text": review})

            payload = res.model_dump() if hasattr(res, "model_dump") else dict(res)
            payload["sample_id"] = int(row["sample_id"])
            payload["hotel_name"] = row["hotel_name"]
            payload["avg_rating"] = float(row["avg_rating"])

            results.append(payload)

            if (i + 1) % 10 == 0:
                print(f"Obrađeno {i+1}/{len(df_sample)}")
            time.sleep(0.5)

        except Exception as e:
            print(f"Greška kod sample_id={row['sample_id']}: {e}")

    with open(LLM_PATH, "w", encoding="utf-8") as f:
        for r in results:
            f.write(json.dumps(r, ensure_ascii=False) + "\n")

    print("Sačuvani LLM rezultati u:", LLM_PATH)

"""U ovom koraku vrši se automatizovana obrada uzorka od 250 recenzija pomoću LLM pipeline-a, uz kontrolisano skladištenje rezultata radi reproduktivnosti analize.

Proces je dizajniran tako da:

1. Proverava da li fajl sa prethodno generisanim LLM rezultatima već postoji.
2. Ako fajl postoji – rezultati se učitavaju iz fajla (bez ponovnog pozivanja LLM-a).
3. Ako fajl ne postoji – pokreće se LLM obrada nad svih 250 recenzija.
4. Dobijeni rezultati se trajno čuvaju u `.jsonl` formatu.

Ovakav pristup omogućava:

- stabilnost eksperimenta,
- izbegavanje duplog LLM pozivanja,
- konzistentnost mrežne analize,
- kontrolu troškova i vremena izvršavanja.

Za svaku recenziju, pored ekstraktovanih sentiment podataka, dodaju se i:

- `sample_id` – jedinstveni identifikator iz uzorka,
- `hotel_name` – naziv hotela,
- `avg_rating` – numerička ocena korisnika.

Time se omogućava:

- kasnije povezivanje sentiment profila sa hotelom,
- validacija sentiment rezultata u odnosu na numeričku ocenu,
- fleksibilnija konstrukcija mreže.

Rezultati se čuvaju u JSON Lines formatu, gde svaka linija predstavlja jednu recenziju sa sledećom strukturom:

- opšti sentiment,
- sentiment po aspektima,
- lista pomenutih sadržaja,
- pozitivne i negativne fraze,
- indikator preporuke,
- metapodaci (`sample_id`, `hotel_name`, `avg_rating`).

Ključna prednost ovakvog pristupa je to što se:

- LLM pozivi izvršavaju samo jednom,
- rezultati trajno čuvaju,
- mrežna analiza uvek vrši nad istim skupom podataka.
"""

files.download(LLM_PATH)

"""## Kreiranje DataFrame strukture iz LLM rezultata"""

llm_df = pd.DataFrame(results)
print("LLM DF shape:", llm_df.shape)
llm_df.head()

"""Nakon završetka LLM obrade i učitavanja rezultata iz `.jsonl` fajla, svi strukturirani izlazi konvertovani su u Pandas DataFrame (`llm_df`).

Dimenzije dobijene strukture su:

- **228 redova** (uspešno parsiranih instanci),
- **9 kolona** koje obuhvataju sentiment i prateće metapodatke.

Važno je napomenuti da je inicijalno obrađeno 250 recenzija, dok deo instanci nije uspešno parsiran usled:
- API rate limit ograničenja,
- neusaglašenosti izlaza sa definisanom Pydantic šemom.

Analiza je sprovedena nad uspešno validiranim instancama.

Svaki red predstavlja jedan sentiment profil korisničke recenzije i sadrži sledeće atribute:

- **overall_sentiment** – opšti sentiment recenzije (positive / neutral / negative)
- **aspects_sentiment** – sentiment po aspektima usluge (čistoća, lokacija, osoblje, komfor, sadržaji, WiFi, hrana, value for money)
- **mentioned_amenities** – lista pomenutih sadržaja
- **complaints** – identifikovane negativne fraze
- **praises** – identifikovane pozitivne fraze
- **would_recommend** – indikator preporuke hotela (True/False)
- **sample_id** – identifikator recenzije iz uzorka
- **hotel_name** – naziv hotela
- **avg_rating** – numerička ocena korisnika

Ovakva struktura omogućava:

- direktno poređenje LLM sentimenta i numeričke ocene,
- kvantifikaciju pozitivnih i negativnih aspekata,
- analizu uticaja pojedinačnih aspekata na ukupni sentiment.

##Analiza uticaja pojedinačnih faktora
"""

llm_df["overall_sentiment"].value_counts(dropna=False)

"""Analizom 228 uspešno parsiranih instanci dobijena je sledeća distribucija vrednosti u koloni `overall_sentiment`:

- **None**: 142
- **positive**: 46
- **negative**: 28
- **neutral**: 12

Može se uočiti da kod značajnog broja instanci (142 / 228 ≈ 62%) sentiment nije eksplicitno klasifikovan od strane modela, te je vrednost ostala `None`.

Ovakav rezultat može biti posledica:
- nedovoljno eksplicitno izraženog opšteg tona u recenziji,
- stroge validacije strukturiranog izlaza,
- ili konzervativnog ponašanja modela koji ne dodeljuje klasu ukoliko nije siguran.

U daljoj analizi sentimenta razmatrane su samo instance sa definisanom vrednošću (`positive`, `negative`, `neutral`), što ukupno čini 86 recenzija.

Distribucija validnih sentiment klasa (n = 86):

- **positive**: 46 (≈53%)
- **negative**: 28 (≈33%)
- **neutral**: 12 (≈14%)

Rezultati pokazuju dominaciju pozitivnih iskustava, ali i značajan udeo negativnih recenzija, dok je neutralni ton najmanje zastupljen – što je u skladu sa tipičnim obrascem ponašanja korisnika prilikom ostavljanja recenzija.

"""

llm_df["overall_sentiment"].value_counts().plot(kind="bar")
plt.title("Distribucija opšteg sentimenta (LLM)")
plt.xlabel("Sentiment")
plt.ylabel("Broj recenzija")
plt.xticks(rotation=0)
plt.show()

"""Na grafiku je prikazana raspodela opšteg sentimenta generisanog pomoću LLM modela, pri čemu su razmatrane samo instance sa eksplicitno dodeljenom klasom (n = 86).

Može se uočiti:

- dominacija pozitivnih recenzija (46),
- značajan broj negativnih (28),
- najmanji udeo neutralnih (12).

Ovakva raspodela ukazuje na polarizaciju korisničkih iskustava, gde preovlađuju jasno izraženi stavovi (pozitivni ili negativni), dok je neutralan ton znatno ređi.

Vizuelni prikaz dodatno potvrđuje numeričku analizu i omogućava intuitivno sagledavanje strukture sentimenta u uzorku.

"""

llm_df["would_recommend"].value_counts()

"""Analizom 115 instanci sa definisanom vrednošću promenljive `would_recommend` dobijena je sledeća raspodela:

- **true**: 58 (≈50%)
- **false**: 27 (≈23%)
- **unknown**: 30 (≈26%)

Rezultati pokazuju da približno polovina korisnika eksplicitno navodi da bi preporučila hotel, dok gotovo četvrtina jasno izražava da ne bi preporučila uslugu.

Značajan udeo kategorije `unknown` (≈26%) ukazuje na to da u određenom broju recenzija preporuka nije bila eksplicitno izražena, odnosno model nije mogao sa sigurnošću da zaključi postojanje namere preporuke na osnovu sadržaja teksta.

Ovakva raspodela je u skladu sa prethodno uočenom dominacijom pozitivnog sentimenta i ukazuje na konzistentnost modela u proceni zadovoljstva i namere preporuke.

"""

df_rel = llm_df[
    llm_df["overall_sentiment"].notna() &
    llm_df["would_recommend"].notna()
]

ct = pd.crosstab(
    df_rel["overall_sentiment"],
    df_rel["would_recommend"]
)

ct

"""Kreirana je kontingenciona tabela između opšteg sentimenta recenzije (`overall_sentiment`) i promenljive `would_recommend`.  
U analizu su uključene samo instance kod kojih obe promenljive imaju definisanu vrednost (izbačeni su zapisi sa `None`).

Rezultati pokazuju sledeći obrazac:

- Kod **pozitivnih** recenzija preporuka hotela je u svim slučajevima označena kao **true** (46/46).
- Kod **negativnih** recenzija preporuka se ne pojavljuje kao **true**, dominira **false**, uz manji deo slučajeva označenih kao **unknown**.
- Kod **neutralnih** recenzija preporuka je češće neodlučna, odnosno prisutna je veća zastupljenost kategorije **unknown**, uz manji broj slučajeva gde je preporuka **true**.

Ovi nalazi ukazuju na **unutrašnju konzistentnost LLM ekstrakcije**: kada model prepozna jasan pozitivan ton, često prepoznaje i nameru preporuke, dok kod neutralnih i negativnih recenzija preporuka ostaje negativna ili neodređena.  
Međutim, interpretaciju treba posmatrati u kontekstu ograničenja uzorka i činjenice da je kategorija `unknown` prisutna kada recenzija ne sadrži eksplicitnu formulaciju preporuke.
"""

df_rel = llm_df[llm_df["overall_sentiment"].notna()]

cleanliness_series = df_rel["aspects_sentiment"].apply(
    lambda d: (d or {}).get("cleanliness")
)

ct_clean = pd.crosstab(
    cleanliness_series,
    df_rel["overall_sentiment"]
)

ct_clean

ct_cleanliness_percent = pd.crosstab(
    cleanliness_series,
    df_rel["overall_sentiment"],
    normalize="index"
)

ct_cleanliness_percent

"""Radi ispitivanja potencijalne povezanosti između percepcije čistoće i ukupnog utiska korisnika, formirana je kontingenciona tabela između sentimenta aspekta **cleanliness** i promenljive **overall_sentiment**.  

U analizu su uključene samo instance sa definisanim opštim sentimentom.

Rezultati pokazuju sledeće obrasce:

- Kada je čistoća ocenjena kao **negative**, ukupni sentiment je češće negativan, ali su prisutni i neutralni i pozitivni slučajevi.
- Kada je čistoća ocenjena kao **positive**, dominantan je pozitivan ukupni sentiment u okviru ove podgrupe, uz manji broj neutralnih i negativnih recenzija.
- U značajnom broju slučajeva čistoća je označena kao **not_mentioned**, što znači da aspekt nije eksplicitno pomenut ili nije izdvojen od strane modela.

Zbog visoke zastupljenosti kategorije `not_mentioned`, nije moguće donositi snažne uzročno-posledične zaključke o ulozi čistoće u formiranju ukupnog sentimenta.  

Ipak, rezultati sugerišu da kada je čistoća eksplicitno ocenjena (pozitivno ili negativno), njen sentiment često ide u istom smeru kao i ukupni utisak recenzije. Ovaj nalaz može ukazivati da čistoća predstavlja relevantan signal u recenzijama u kojima se eksplicitno ističe, ali ne i dominantan faktor u svim slučajevima.

"""

df_rel = llm_df[llm_df["overall_sentiment"].notna()]

location_series = df_rel["aspects_sentiment"].apply(
    lambda d: (d or {}).get("location")
)

ct_location = pd.crosstab(
    location_series,
    df_rel["overall_sentiment"]
)

ct_location

ct_location_percent = pd.crosstab(
    location_series,
    df_rel["overall_sentiment"],
    normalize="index"
)

ct_location_percent

"""Radi ispitivanja potencijalne povezanosti između percepcije lokacije hotela i ukupnog utiska korisnika, formirana je kontingenciona tabela između sentimenta aspekta **location** i promenljive **overall_sentiment**. U analizu su uključene samo instance sa definisanim opštim sentimentom.

Rezultati pokazuju sledeće obrasce:

- Kada je lokacija ocenjena kao **positive**, u većini slučajeva dominira pozitivan ukupni sentiment (≈62% unutar ove podgrupe).
- Kada je lokacija ocenjena kao **negative**, broj instanci je veoma mali, te nije moguće donositi pouzdane zaključke o obrascu povezanosti.
- U značajnom broju recenzija lokacija je označena kao **not_mentioned**, pri čemu je raspodela ukupnog sentimenta relativno uravnotežena između pozitivnih i negativnih ocena.

Na osnovu ovih podataka može se zaključiti da pozitivna percepcija lokacije često korespondira sa pozitivnim ukupnim utiskom, ali zbog ograničenog broja negativnih instanci i visoke zastupljenosti kategorije `not_mentioned`, nije moguće donositi snažne uzročno-posledične zaključke o njenom uticaju.

"""

df_rel = llm_df[llm_df["overall_sentiment"].notna()]

staff_series = df_rel["aspects_sentiment"].apply(
    lambda d: (d or {}).get("staff")
)

ct_staff = pd.crosstab(
    staff_series,
    df_rel["overall_sentiment"]
)

ct_staff

ct_staff_percent = pd.crosstab(
    staff_series,
    df_rel["overall_sentiment"],
    normalize="index"
)

ct_staff_percent

"""Radi ispitivanja potencijalne povezanosti između percepcije osoblja hotela i ukupnog utiska korisnika, formirana je kontingenciona tabela između sentimenta aspekta **staff** i promenljive **overall_sentiment**. U analizu su uključene samo instance sa definisanim opštim sentimentom.

Rezultati ukazuju na sledeće obrasce:

- Kada je osoblje ocenjena kao **negative**, ukupni sentiment je u svim analiziranim slučajevima negativan (n=4).
- Kada je sentiment prema osoblju **neutral**, ukupni sentiment je takođe neutralan (n=2).
- Kada je osoblje ocenjeno kao **positive**, u većini slučajeva dominira pozitivan ukupni sentiment (≈71% unutar ove podgrupe).
- Kada osoblje nije eksplicitno pomenuto (`not_mentioned`), raspodela ukupnog sentimenta je relativno uravnotežena.

Iako ovi rezultati sugerišu da percepcija osoblja često ide u istom smeru kao i ukupni utisak recenzije, potrebno je napomenuti da su pojedine kategorije (naročito negativne i neutralne ocene osoblja) zastupljene u malom broju instanci. Stoga se nalazi mogu posmatrati kao indikativni, ali ne i kao dokaz snažne uzročne povezanosti.

"""

df_rel = llm_df[llm_df["overall_sentiment"].notna()]

comfort_series = df_rel["aspects_sentiment"].apply(
    lambda d: (d or {}).get("comfort")
)

ct_comfort = pd.crosstab(
    comfort_series,
    df_rel["overall_sentiment"]
)

ct_comfort

ct_comfort_percent = pd.crosstab(
    comfort_series,
    df_rel["overall_sentiment"],
    normalize="index"
)

ct_comfort_percent

"""Radi ispitivanja potencijalne povezanosti između percepcije udobnosti i ukupnog utiska korisnika, formirana je kontingenciona tabela između sentimenta aspekta **comfort** i promenljive **overall_sentiment**. U analizu su uključene samo instance sa definisanim opštim sentimentom.

Rezultati pokazuju sledeće obrasce:

- Kada je udobnost ocenjena kao **negative**, u većini slučajeva (≈64%) ukupni sentiment je negativan, uz manji broj neutralnih i pozitivnih ocena.
- Kada je udobnost ocenjena kao **positive**, dominantan je pozitivan ukupni sentiment (≈73% unutar te podgrupe).
- Kada udobnost nije eksplicitno pomenuta (`not_mentioned`), ukupni sentiment je u velikoj meri pozitivan, što ukazuje da drugi aspekti verovatno imaju značajnu ulogu u formiranju ukupnog utiska.
- Kategorija **neutral** je zastupljena u veoma malom broju instanci, te nije moguće donositi pouzdane zaključke na osnovu te podgrupe.

Ovi nalazi sugerišu da sentiment vezan za udobnost često ide u istom smeru kao i ukupni sentiment recenzije. Ipak, zbog ograničenja uzorka i činjenice da svi aspekti nisu podjednako zastupljeni u recenzijama, rezultati se mogu posmatrati kao indikativni, ali ne i kao dokaz snažne uzročne povezanosti.

### Zaključna analiza uticaja aspekata usluge na opšti sentiment

Analiza povezanosti sentimenta po aspektima (čistoća, lokacija, osoblje, udobnost) sa opštim sentimentom ukazuje na uočljive, ali umerene obrasce koji sugerišu internu konzistentnost LLM modela.

Najvažniji nalazi:

- **Čistoća** pokazuje primetnu usklađenost sa opštim sentimentom.  
  Kada je čistoća ocenjena negativno, ukupni sentiment je češće negativan, dok pozitivna ocena čistoće u većini slučajeva korespondira sa pozitivnim ukupnim utiskom. Ipak, značajan broj recenzija u kojima čistoća nije pomenuta ograničava donošenje snažnijih zaključaka o njenom uticaju.

- **Udobnost (comfort)** pokazuje relativno izraženu povezanost sa opštim sentimentom.  
  Negativne ocene udobnosti češće su praćene negativnim ukupnim sentimentom, dok pozitivne ocene u većini slučajeva prate pozitivan ukupni utisak. Međutim, raspodela podataka i veličina pojedinih podgrupa zahtevaju oprez u interpretaciji. Takođe kada udobnost nije pomenuta onda ukupni sentiment pozitivan što jasno ukazuje na dominatnost ostalih aspekata pri povezanosti sa ukupnim sentimentom.

- **Osoblje (staff)** pokazuje dosledan smer sentimenta u analiziranim instancama.  
  Kada je osoblje ocenjena negativno, ukupni sentiment je negativan, dok pozitivna percepcija osoblja u većini slučajeva prati pozitivan opšti utisak. Ipak, neke kategorije su zastupljene u manjem broju instanci, te se nalazi mogu posmatrati kao indikativni.

- **Lokacija** pokazuje umeren obrazac povezanosti.  
  Pozitivna percepcija lokacije često je praćena pozitivnim ukupnim sentimentom, ali zbog malog broja negativnih instanci i česte kategorije `not_mentioned`, nije moguće govoriti o snažnoj povezanosti.

Opšti zaključak:

Rezultati ukazuju da LLM model generiše logički i semantički usklađene procene između pojedinačnih aspekata i ukupnog sentimenta recenzije. U slučajevima kada je određeni aspekt eksplicitno ocenjen (pozitivno ili negativno), njegov sentiment često ide u istom smeru kao i opšti utisak.

## Statistička analiza povezanosti sentimenta i preporuke

Na osnovu 86 instanci sa definisanim opštim sentimentom dobijena je sledeća distribucija:

- Pozitivne recenzije: 46 (≈53%)
- Negativne recenzije: 28 (≈33%)
- Neutralne recenzije: 12 (≈14%)

Distribucija preporuke hotela (115 instanci sa definisanom vrednošću):

- Preporučuje hotel (true): 58 (≈50%)
- Ne preporučuje (false): 27 (≈23%)
- Nije jasno (unknown): 30 (≈26%)

### Povezanost sentimenta i preporuke

Analiza ukrštene tabele između opšteg sentimenta i promenljive `would_recommend` pokazuje uočljiv obrazac usklađenosti:

- Pozitivne recenzije u svim analiziranim slučajevima rezultiraju preporukom hotela.
- Kod negativnih recenzija preporuka se ne pojavljuje kao „true“, već dominira „false“, uz manji broj slučajeva označenih kao „unknown“.
- Neutralne recenzije pokazuju mešovit obrazac, sa izraženijom zastupljenošću kategorije „unknown“.

Ovaj odnos ukazuje na internu konzistentnost LLM ekstrakcije – kada model identifikuje jasan pozitivan ton, često prepoznaje i nameru preporuke. Ipak, interpretaciju treba posmatrati u kontekstu ograničenja uzorka i prisustva kategorije „unknown“, koja označava odsustvo eksplicitne formulacije preporuke u tekstu.
"""

df_rel = llm_df[
    llm_df["overall_sentiment"].notna() &
    llm_df["would_recommend"].notna()
]


ct = pd.crosstab(
    df_rel["overall_sentiment"],
    df_rel["would_recommend"]
)

matrix = ct.values


plt.figure(figsize=(6, 5))
plt.imshow(matrix)
plt.colorbar(label="Broj recenzija")
plt.xticks(range(len(ct.columns)), ct.columns)
plt.yticks(range(len(ct.index)), ct.index)
plt.xlabel("Would Recommend")
plt.ylabel("Overall Sentiment")
plt.title("Heatmap: Overall Sentiment vs Recommendation")
for i in range(matrix.shape[0]):
    for j in range(matrix.shape[1]):
        plt.text(j, i, matrix[i, j],
                 ha="center", va="center")
plt.tight_layout()
plt.show()

"""Na prikazanom heatmap grafiku predstavljena je kontingenciona tabela između promenljivih `overall_sentiment` i `would_recommend`, pri čemu su uključene samo instance sa definisanim vrednostima obe promenljive.

Uočavaju se sledeći obrasci:

- Sve pozitivne recenzije (46) rezultirale su preporukom hotela (`true`).
- Kod negativnih recenzija dominantna je kategorija `false` (23), dok manji broj slučajeva pripada kategoriji `unknown` (4). Preporuka `true` se ne pojavljuje.
- Neutralne recenzije pokazuju podeljen obrazac: manji broj rezultira preporukom (3), dok je veći deo klasifikovan kao `unknown` (9).

Vizuelni prikaz dodatno potvrđuje numeričku analizu i ukazuje na izraženu usklađenost između opšteg sentimenta i namere preporuke.

Ipak, prisustvo kategorije `unknown` sugeriše da u određenom broju recenzija preporuka nije eksplicitno formulisana, što ograničava mogućnost donošenja snažnih zaključaka o preciznoj jačini ove povezanosti.

### Analiza aspekata

Analiza povezanosti pojedinačnih aspekata (čistoća, lokacija, osoblje, udobnost) sa opštim sentimentom pokazuje umerene i konzistentne obrasce:

- Čistoća, udobnost i osoblje češće prate smer opšteg sentimenta kada su eksplicitno ocenjeni.
- Lokacija pokazuje umeren obrazac povezanosti, uz manji broj negativnih instanci.
- U svim aspektima značajan deo recenzija sadrži kategoriju „not_mentioned“, što ograničava mogućnost preciznog poređenja relativne važnosti faktora.

Ovi nalazi sugerišu da strukturirana LLM ekstrakcija reflektuje logične odnose prisutne u tekstualnim recenzijama, ali ne omogućava precizno rangiranje faktora koji utiču na ukupni sentiment.

### Zaključak statističke analize

Rezultati ukazuju da LLM model generiše semantički dosledne i međusobno usklađene procene između aspekata, opšteg sentimenta i namere preporuke. U slučajevima kada je određeni aspekt jasno ocenjen (pozitivno ili negativno), njegov sentiment često ide u istom smeru kao i ukupni utisak.

Međutim, zbog neravnomerne zastupljenosti pojedinih kategorija, prisustva „not_mentioned“ vrednosti i ograničenog broja instanci u nekim podgrupama, nalazi se mogu posmatrati kao indikativni obrasci, a ne kao dokaz snažne uzročne povezanosti između pojedinačnih faktora i ukupnog zadovoljstva korisnika.

## Validacija LLM rezultata sa numerickom ocenom
"""

df_sample = df_sample.copy().reset_index(drop=True)
df_sample["sample_id"] = df_sample.index.astype(int)

llm_df_map = llm_df[["sample_id", "overall_sentiment", "would_recommend"]].copy()

merged = df_sample.merge(llm_df_map, on="sample_id", how="left")

validation_df = merged[
    merged["rating_category"].notna() &
    merged["overall_sentiment"].notna()
].copy()

validation_df["llm_sentiment"] = validation_df["overall_sentiment"]

ct = pd.crosstab(validation_df["llm_sentiment"], validation_df["rating_category"])

ct

merged.shape, validation_df.shape

accuracy = (validation_df["llm_sentiment"] == validation_df["rating_category"]).mean()
accuracy

"""Izvršeno je poređenje LLM-ekstrahovanog sentimenta sa kategorijom izvedenom iz numeričke ocene hotela.

Numeričke ocene su transformisane u tri klase:

- **positive** (rating ≥ 8)
- **neutral** (6 ≤ rating < 8)
- **negative** (rating < 6)

Validacija je sprovedena nad podskupom od **86 recenzija** kod kojih su obe vrednosti (`overall_sentiment` i `rating_category`) bile definisane.

Ukupna tačnost poklapanja iznosi približno **53.5%**.

Rezultati ukazuju na umereno slaganje između LLM interpretacije tekstualnog sadržaja i kategorije izvedene iz numeričke ocene.
"""

labels = ["negative", "neutral", "positive"]

cm = confusion_matrix(
    validation_df["rating_category"],
    validation_df["llm_sentiment"],
    labels=labels
)

disp = ConfusionMatrixDisplay(confusion_matrix=cm, display_labels=labels)

disp.plot(cmap="Blues", values_format="d")
plt.title("Matrica konfuzije: LLM sentiment vs Rating kategorija")
plt.xlabel("Predikcija (LLM sentiment)")
plt.ylabel("Stvarna klasa (rating_category)")
plt.show()

"""Analiza matrice konfuzije pokazuje da:

- Pozitivne LLM klasifikacije u značajnom broju slučajeva odgovaraju pozitivnim numeričkim ocenama.
- LLM model identifikuje negativan sentiment i u slučajevima kada je numerička ocena pozitivna.
- U validacionom podskupu nije prisutna negativna kategorija u `rating_category`, što utiče na raspodelu i interpretaciju metrike tačnosti.

Tekstualni sadržaj može sadržati kritičke elemente koji nisu u potpunosti reflektovani kroz numeričku vrednost ocene.

Dobijeni nalazi sugerišu da LLM model prepoznaje semantičke nijanse u korisničkim komentarima, ali i da postoji razlika između kvantitativne (numeričke) i kvalitativne (tekstualne) procene zadovoljstva.
"""

y_true = validation_df["rating_category"].astype(str)
y_pred = validation_df["llm_sentiment"].astype(str)


labels = ["negative", "neutral", "positive"]


bacc = balanced_accuracy_score(y_true, y_pred)
f1_macro = f1_score(y_true, y_pred, labels=labels, average="macro", zero_division=0)
f1_weighted = f1_score(y_true, y_pred, labels=labels, average="weighted", zero_division=0)

print(f"Validacioni skup (n) = {len(validation_df)}")
print(f"Balanced accuracy = {bacc:.3f}")
print(f"F1-macro = {f1_macro:.3f}")
print(f"F1-weighted = {f1_weighted:.3f}")


print("\nClassification report (rating_category -> llm_sentiment):")
print(classification_report(
    y_true, y_pred,
    labels=labels,
    digits=3,
    zero_division=0
))


print("\nDistribucija rating_category (y_true):")
print(y_true.value_counts(dropna=False))

print("\nDistribucija llm_sentiment (y_pred):")
print(y_pred.value_counts(dropna=False))

"""Radi detaljnije procene slaganja između LLM-ekstrahovanog sentimenta i kategorisane numeričke ocene hotela, izračunate su standardne klasifikacione metrike: accuracy, balanced accuracy, precision, recall i F1-score.

Validacija je sprovedena nad podskupom od **86 recenzija** kod kojih su obe vrednosti (`rating_category` i `overall_sentiment`) bile definisane.

Rezultati:

- **Ukupna tačnost (Accuracy): 0.535**
- **Balanced accuracy: 0.535**
- **F1-macro: 0.232**
- **F1-weighted: 0.697**

Distribucija stvarnih klasa (`rating_category`):

- positive: 86  
- neutral: 0  
- negative: 0  

Distribucija LLM predikcija (`overall_sentiment`):

- positive: 46  
- negative: 28  
- neutral: 12  

Rezultati ukazuju na specifičnu strukturu validacionog skupa – sve stvarne instance pripadaju klasi **positive**, dok LLM model generiše i negativne i neutralne predikcije.

Zbog toga:

- precision i recall za klase `negative` i `neutral` iznose 0, jer te klase ne postoje u stvarnim podacima,
- balanced accuracy je identična accuracy metriki,
- macro F1 je nizak (0.232) jer se računa prosečno preko svih klasa,
- weighted F1 je visok (0.697) jer je jedina stvarna klasa `positive`.

Ovakva distribucija ukazuje da numerička ocena u validacionom podskupu ne sadrži negativne instance, dok tekstualna analiza pomoću LLM modela prepoznaje izražene negativne i neutralne elemente u sadržaju recenzija.

To potvrđuje da numerička ocena i tekstualni sentiment ne predstavljaju identične dimenzije evaluacije. Numerička ocena reflektuje globalni utisak korisnika, dok LLM analiza detektuje konkretne pozitivne i negativne aspekte izražene u tekstu.

## Mrežna analiza korisnika na osnovu sličnosti sentiment profila

Nakon ekstrakcije strukturiranih informacija pomoću LLM modela, konstruisan je prošireni dataset koji omogućava analizu sličnosti između sentiment profila recenzija.

U ovoj fazi primenjuje se mrežna analiza, gde:

- Čvorovi (nodes) predstavljaju pojedinačne recenzije, pri čemu se svaka recenzija tretira kao jedinstven sentiment profil (proxy korisnika).
- Ivica (edge) između dva čvora postoji ukoliko je kosinusna sličnost njihovih aspektnih sentiment profila veća ili jednaka definisanom pragu (τ = 0.7).
- Težina veze definisana je vrednošću cosine similarity između vektora aspekata sentimenta.

Za merenje sličnosti koristi se **cosine similarity** mera, koja kvantifikuje koliko su obrasci zadovoljstva po aspektima (cleanliness, location, staff, comfort, facilities, value_for_money, wifi, food) međusobno slični.

Važna metodološka napomena je da u realnom scenariju jedan korisnik može imati više recenzija, te bi idealno bilo agregirati recenzije po korisniku i formirati jedinstven sentiment profil. Međutim, zbog ograničenja dostupnih podataka, u ovom radu svaka recenzija se tretira kao zaseban profil.

Stoga mreža ne predstavlja socijalnu mrežu korisnika, već mrežu sličnosti percepcije kvaliteta usluge.
"""

sentiment_map = {
    "negative": -1,
    "neutral": 0,
    "positive": 1,
    "not_mentioned": 0
}

aspect_cols = ["cleanliness", "location", "staff", "comfort",
               "facilities", "value_for_money", "wifi", "food"]

profiles = []
nonzero_counts = []

for aspects in llm_df["aspects_sentiment"]:
    aspects = aspects or {}
    vector = [sentiment_map.get(aspects.get(a), 0) for a in aspect_cols]
    profiles.append(vector)
    nonzero_counts.append(sum(v != 0 for v in vector))

profiles = np.array(profiles)

print("Profiles shape:", profiles.shape)
print("Prosečno pomenutih aspekata po recenziji:", np.mean(nonzero_counts))
print("Broj recenzija sa 0 pomenutih aspekata:", np.sum(np.array(nonzero_counts) == 0))


MIN_MENTIONED = 2
mask = np.array(nonzero_counts) >= MIN_MENTIONED

profiles_f = profiles[mask]
llm_df_f = llm_df[mask].reset_index(drop=True)

print("Nakon filtriranja shape:", profiles_f.shape)

"""U cilju sprovođenja mrežne analize, aspektni sentimenti su transformisani u numeričke vrednosti:

- **positive → 1**
- **neutral → 0**
- **negative → -1**
- **not_mentioned → 0**

Na ovaj način svaka recenzija se predstavlja kao **vektor dužine 8**, gde svaka komponenta odgovara jednom aspektu usluge:

- cleanliness  
- location  
- staff  
- comfort  
- facilities  
- value_for_money  
- wifi  
- food  

Formirana je matrica `profiles` dimenzije **(228, 8)**, koja predstavlja numeričke sentiment profile recenzija uspešno obrađenih od strane LLM modela.

Dodatnom analizom utvrđeno je:

- Prosečan broj eksplicitno pomenutih aspekata po recenziji iznosi približno **1.70**
- **100 recenzija** nema nijedan eksplicitno pomenut aspekt (sve komponente vektora jednake su 0)

Recenzije bez pomenutih aspekata predstavljaju nula-vektore, koji ne nose informaciju o obrascu zadovoljstva i mogu narušiti validnost kosinusne sličnosti u mrežnoj analizi.

Kako bi se obezbedila stabilnost i interpretabilnost mrežne strukture, izvršeno je filtriranje recenzija sa manje od **2 pomenuta aspekta**.

Nakon primene ovog kriterijuma:

- Zadržano je **108 recenzija**
- Dobijena matrica `profiles_f` ima dimenziju **(108, 8)**

Na ovaj način mrežna analiza se zasniva isključivo na recenzijama koje sadrže dovoljan broj informativnih aspekata, čime se:

- smanjuje šum u podacima  
- izbegava veštačka sličnost nula-vektora  
- povećava stabilnost detekcije zajednica  
- poboljšava interpretabilnost centralnosti i strukture mreže  

Dobijeni filtrirani profilni vektori predstavljaju validnu osnovu za izračunavanje kosinusne sličnosti i konstrukciju mreže korisnika.

"""

similarity_matrix = cosine_similarity(profiles_f)

print("Similarity matrix shape:", similarity_matrix.shape)

similarity_matrix[:5, :5]

"""Nakon filtriranja neinformativnih instanci (recenzija sa manje od 2 pomenuta aspekta), dobijena je matrica profilnih vektora `profiles_f` dimenzije **(108, 8)**.

Nad ovom matricom izračunata je **kosinusna sličnost (cosine similarity)** između svih parova recenzija:

Kosinusna sličnost meri ugaonu sličnost između dva vektora i uzima vrednosti u opsegu:

- **1** → identični obrasci sentimenta  
- **0** → bez sličnosti  
- **-1** → suprotni obrasci sentimenta  

U posmatranim podacima vrednosti se kreću od 0 do 1, što ukazuje da recenzije nemaju potpuno suprotne sentiment profile, već se razlikuju po intenzitetu i kombinaciji aspekata.

Dijagonala matrice ima vrednost 1, što znači da je svaka recenzija maksimalno slična samoj sebi.

Dobijena matrica `similarity_matrix` predstavlja osnovu za:

- konstrukciju mreže sličnosti recenzija,
- definisanje ivica između čvorova na osnovu praga sličnosti,
- analizu centralnosti,
- detekciju zajednica (community detection).

Filtriranje nula-vektora pre izračunavanja sličnosti omogućilo je stabilniju i interpretabilniju mrežnu strukturu, jer su uklonjene recenzije bez informativnog aspektnog sadržaja.

### Konstrukcija mreže korisnika
"""

threshold = 0.7

N = profiles_f.shape[0]

G = nx.Graph()

G.add_nodes_from(range(N))

for i in range(N):
    for j in range(i + 1, N):
        sim = similarity_matrix[i, j]
        if sim >= threshold:
            G.add_edge(i, j, weight=float(sim))

print("Broj čvorova:", G.number_of_nodes())
print("Broj ivica:", G.number_of_edges())
print("Gustina mreže:", nx.density(G))

"""Na osnovu matrice kosinusne sličnosti `similarity_matrix` konstruisana je **neusmerena mreža sličnosti** (NetworkX `Graph`) nad filtriranim skupom recenzija. U prethodnom koraku zadržane su samo informativne recenzije (sa najmanje 2 pomenuta aspekta), čime je dobijeno ukupno **N = 108** profilnih vektora (`profiles_f`).

**Definicija mreže:**
- **Čvor (node)** predstavlja jednu recenziju (proxy korisničkog sentiment profila).
- **Ivica (edge)** između čvorova *i* i *j* dodaje se ako je kosinusna sličnost njihovih profilnih vektora **≥ 0.7**.
- **Težina ivice** jednaka je vrednosti kosinusne sličnosti, tj. `weight = similarity_matrix[i, j]`.

Prag **0.7** je odabran kao konzervativan kriterijum koji obezbeđuje da se u mrežu uključe samo **relativno jake sličnosti** između sentiment profila. U kontekstu vektora aspekata (vrednosti -1, 0, 1) niži pragovi (npr. 0.3–0.5) često uvode veliki broj slabih veza koje mogu nastati zbog velikog broja nula (`not_mentioned`), čime mreža postaje previše “zbijena” i manje interpretabilna.

Sa pragom 0.7:
- smanjuje se šum i broj slučajnih/nekorisnih veza,
- dobijaju se jasnije i smislenije zajednice (community strukture),
- centralnost čvorova ima veću interpretativnu vrednost (čvor je centralan jer je **zaista sličan** mnogima, ne zato što je prag prenizak).

Drugim rečima, prag 0.7 predstavlja kompromis - mreža ostaje dovoljno povezana za analizu, ali je istovremeno dovoljno “stroga” da veze nose semantičko značenje.

- **Broj čvorova:** 108  
- **Broj ivica:** 530  
- **Gustina mreže:** 0.0917  

Dobijena mreža ukazuje na postojanje značajnog broja recenzija sa sličnim obrascima aspektnih sentimenta, što opravdava primenu mrežne analize za dalju identifikaciju zajednica i analizu centralnosti.

### Vizuelna analiza mreže sličnosti recenzija
"""

plt.figure(figsize=(10, 8))

pos = nx.spring_layout(G, seed=42, k=0.25)


weights = [G[u][v].get("weight", 1.0) for u, v in G.edges()]

edge_widths = [1 + 3*(w - 0.7) for w in weights]

nx.draw_networkx_nodes(G, pos, node_size=40)
nx.draw_networkx_edges(G, pos, width=edge_widths, alpha=0.35)

plt.title("Mreža recenzija zasnovana na sličnosti aspektnih sentiment profila (threshold = 0.7)")
plt.axis("off")
plt.show()

"""Primenom praga kosinusne sličnosti od 0.7 konstruisana je neusmerena mreža nad 108 recenzija.

Vizuelizacija mreže pokazuje sledeće strukturne karakteristike:

- Postojanje jedne dominantne povezane komponente sa visokom gustinom veza.
- Manji broj perifernih i izolovanih čvorova.
- Prisustvo manjih podgrupa unutar centralne komponente.

Centralna komponenta ukazuje na grupu recenzija sa izraženim međusobnim sličnostima u aspektnim sentiment profilima. Ovi čvorovi dele slične obrasce evaluacije hotela (npr. slične kombinacije pozitivnih i negativnih aspekata).

Periferni i izolovani čvorovi predstavljaju recenzije čiji aspektni profili značajno odstupaju od dominantnog obrasca, odnosno nemaju kosinusnu sličnost ≥ 0.7 sa dovoljnim brojem drugih recenzija.

Ovakva struktura sugeriše:

- postojanje dominantnog obrasca percepcije kvaliteta usluge među većinom korisnika,
- ali i prisustvo specifičnih ili individualnih obrazaca zadovoljstva kod manjeg broja korisnika.

Relativno niska gustina mreže (~0.09) potvrđuje da su veze formirane samo između recenzija sa snažnom sličnosti, što dodatno opravdava izbor praga 0.7 kao kriterijuma za definisanje relevantnih veza.

### Analiza centralnosti: Degree centrality
"""

degree_centrality = nx.degree_centrality(G)

degree_df = (
    pd.DataFrame(degree_centrality.items(), columns=["node", "degree_centrality"])
    .sort_values("degree_centrality", ascending=False)
    .reset_index(drop=True)
)

degree_df.head(5)

degree_raw = dict(G.degree())

degree_raw_df = (
    pd.DataFrame(degree_raw.items(), columns=["node", "degree"])
    .sort_values("degree", ascending=False)
    .reset_index(drop=True)
)

degree_raw_df.head(5)

"""**Degree centrality** meri u kojoj meri je određeni čvor direktno povezan sa drugim čvorovima u mreži. U kontekstu ove analize, visoka vrednost degree centrality ukazuje na recenziju čiji je aspektni sentiment profil sličan velikom broju drugih recenzija (cosine similarity ≥ 0.7).

Prema dobijenim rezultatima, čvorovi 96, 48 , 47 imaju najveću degree centrality vrednost (~0.299), odnosno po **32 direktne veze** u mreži.

Slede čvor 28 (28 veza) i čvor 7 (26 veza).

Ovi čvorovi predstavljaju recenzije koje dele dominantni obrazac percepcije kvaliteta usluge. Njihovi aspektni sentiment profili su visoko usklađeni sa velikim brojem drugih recenzija i mogu se interpretirati kao reprezentativni primeri dominantnog obrasca zadovoljstva u dataset-u.

Drugim rečima, visoka degree centrality identifikuje **tipične ili „prototipske“ sentiment profile**.

### Analiza centralnosti: Betweenness centrality
"""

betweenness = nx.betweenness_centrality(G, normalized=True)

betweenness_df = (
    pd.DataFrame(betweenness.items(), columns=["node", "betweenness_centrality"])
    .sort_values("betweenness_centrality", ascending=False)
    .reset_index(drop=True)
)

betweenness_df.head(5)

betweenness_raw = nx.betweenness_centrality(G, normalized=False)

betweenness_raw_df = (
    pd.DataFrame(betweenness_raw.items(), columns=["node", "betweenness"])
    .sort_values("betweenness", ascending=False)
    .reset_index(drop=True)
)

betweenness_raw_df.head(5)

"""**Betweenness centrality** meri u kojoj meri se određeni čvor nalazi na najkraćim putevima između drugih parova čvorova u mreži. Ova mera identifikuje čvorove koji imaju ulogu posrednika ili „mostova“ između različitih grupa recenzija.

Najveće vrednosti imaju čvorovi:

- 99 (≈ 0.093)
- 37 (≈ 0.091)
- 51 (≈ 0.078)
- 61 (≈ 0.066)
- 13 (≈ 0.059)

Ove recenzije imaju značajnu posredničku ulogu u mreži i povezuju različite podgrupe korisnika sa sličnim, ali ne identičnim aspektnim profilima.

Nenormalizovane vrednosti (npr. čvor 99 ≈ 528) predstavljaju stvaran broj najkraćih puteva koji prolaze kroz dati čvor. Visoke vrednosti potvrđuju da ovi korisnici imaju ključnu strukturalnu poziciju u mreži.

Za razliku od **degree centrality**, koja identifikuje dominantne i tipične obrasce zadovoljstva, **betweenness centrality** otkriva recenzije sa **prelaznim ili hibridnim sentiment profilima**.

Takvi korisnici:

- ne pripadaju isključivo jednoj homogeno pozitivnoj ili negativnoj grupi,
- kombinuju različite aspektne evaluacije,
- povezuju različite grupe percepciae kvaliteta usluge.

Ova razlika potvrđuje da mreža ne predstavlja socijalne interakcije, već strukturu sličnosti percepcije kvaliteta hotela. Degree centrality ukazuje na dominantne obrasce, dok betweenness centrality otkriva strukturalne mostove između njih.

### Detekcija zajednica korisnika
"""

communities_greedy = list(community.greedy_modularity_communities(G))

sizes_greedy = [len(c) for c in communities_greedy]
sizes_greedy_sorted = sorted(sizes_greedy, reverse=True)

print("Greedy: broj zajednica =", len(communities_greedy))
print("Greedy: veličine zajednica (sortirano) =", sizes_greedy_sorted)

Q_greedy = community.modularity(G, communities_greedy, weight="weight")
print("Greedy: modularnost Q =", Q_greedy)

communities_greedy_sorted = sorted(communities_greedy, key=len, reverse=True)
node_to_comm_greedy = {}
for cid, comm in enumerate(communities_greedy_sorted):
    for n in comm:
        node_to_comm_greedy[n] = cid

communities_louvain = list(community.louvain_communities(G, weight="weight", seed=42))

sizes_louvain = sorted([len(c) for c in communities_louvain], reverse=True)
print("Louvain: broj zajednica =", len(communities_louvain))
print("Louvain: veličine zajednica (sortirano) =", sizes_louvain)

Q_louvain = community.modularity(G, communities_louvain, weight="weight")
print("Louvain: modularnost Q =", Q_louvain)

communities_louvain_sorted = sorted(communities_louvain, key=len, reverse=True)
node_to_comm_louvain = {}
for cid, comm in enumerate(communities_louvain_sorted):
    for n in comm:
        node_to_comm_louvain[n] = cid

"""U cilju identifikacije grupa recenzija sa sličnim aspektnim sentiment profilima, primenjena su dva algoritma za detekciju zajednica:

1. **Greedy modularity maximization (Clauset–Newman–Moore pristup)**
2. **Louvain algoritam**

Oba algoritma zasnivaju se na maksimizaciji modularnosti (Q), ali koriste različite heuristike za pronalaženje optimalne podele mreže.

1. Greedy modularity (Clauset–Newman–Moore)

**Greedy modularity algoritam** započinje sa pretpostavkom da je svaki čvor zasebna zajednica, a zatim iterativno spaja parove zajednica čije spajanje najviše povećava modularnost mreže. Proces se nastavlja dok dalja spajanja ne donose poboljšanje modularnosti.

- **Broj zajednica:** 14  
- **Veličine zajednica:**  
  35, 27, 24, 8, 5, 1, 1, 1, 1, 1, 1, 1, 1, 1  
- **Modularnost (Q):** 0.394

Dobijena modularnost (Q ≈ 0.39) ukazuje na izraženu klastersku strukturu. Veće zajednice predstavljaju dominantne obrasce percepcije kvaliteta usluge, dok zajednice veličine 1 odgovaraju izolovanim ili atipičnim sentiment profilima.

2. Louvain algoritam

**Louvain metod** predstavlja napredniju heuristiku za maksimizaciju modularnosti i funkcioniše u dve faze:

1. Lokalno premeštanje čvorova između susednih zajednica radi povećanja modularnosti.
2. Agregacija zajednica u “super-čvorove” i ponavljanje procesa na redukovanoj mreži.

Ovaj pristup je efikasniji kod srednje gustih mreža i često daje stabilnije i finije strukturirane zajednice.

- **Broj zajednica:** 15  
- **Veličine zajednica:**  
  26, 22, 21, 13, 10, 7, 1, 1, 1, 1, 1, 1, 1, 1, 1  
- **Modularnost (Q):** 0.412

Vrednost modularnosti Q ≈ 0.41 ukazuje na još izraženiju i koherentniju zajedničku strukturu u odnosu na greedy pristup.

### Poređenje algoritama

| Algoritam | Broj zajednica | Modularnost (Q) |
|------------|----------------|----------------|
| Greedy     | 14             | 0.394          |
| Louvain    | 15             | 0.412          |

Louvain algoritam postiže višu modularnost, što sugeriše bolju podelu mreže u strukturno koherentne zajednice. Razlike u veličinama zajednica ukazuju na to da Louvain finije razdvaja dominantne klastere, dok greedy pristup formira nešto veće agregirane grupe.

Rezultati oba algoritma potvrđuju postojanje jasno definisanih grupa recenzija sa sličnim aspektnim sentiment profilima. Ove zajednice ne predstavljaju socijalne interakcije korisnika, već klastere percepcije kvaliteta usluge.

Veće zajednice identifikuju dominantne obrasce zadovoljstva, dok manje i izolovane zajednice ukazuju na specifične ili atipične evaluacije hotela.

Bliska vrednost modularnosti u oba pristupa dodatno potvrđuje stabilnost detektovane strukture mreže.

### Izbor algoritma za dalju analizu

Iako su oba algoritma (Greedy modularity i Louvain) identifikovala jasnu zajedničku strukturu u mreži, za dalju analizu korišćen je **Louvain algoritam** iz sledećih razloga:

1. **Viša modularnost (Q = 0.412)**  
   Louvain pristup ostvaruje veću vrednost modularnosti u odnosu na greedy algoritam (Q = 0.394), što ukazuje na kvalitetniju i koherentniju podelu mreže.

2. **Stabilnija i finija segmentacija zajednica**  
   Louvain algoritam iterativno optimizuje modularnost kroz lokalna premeštanja čvorova i agregaciju zajednica, što omogućava preciznije razdvajanje dominantnih klastera.

3. **Šira primena u savremenim mrežnim analizama**  
   Louvain metod predstavlja standard u detekciji zajednica u složenim mrežama, naročito kod mreža srednje gustine i sa težinskim vezama.

4. **Bolja interpretabilnost strukture**  
   Dobijene zajednice su uravnoteženije po veličini i jasnije razdvojene, što olakšava interpretaciju dominantnih i specifičnih obrazaca percepcije kvaliteta usluge.

Na osnovu navedenog, Louvain algoritam je izabran kao primarni metod za interpretaciju zajednica u nastavku rada.

### Analiza strukture unutar detektovanih zajednica
"""

node_to_comm = node_to_comm_louvain

deg_c = nx.degree_centrality(G)
bet_c = nx.betweenness_centrality(G, normalized=True)

rows = []
for cid in sorted(set(node_to_comm.values())):
    nodes = [n for n, c in node_to_comm.items() if c == cid]

    top_deg = sorted(nodes, key=lambda n: deg_c.get(n, 0), reverse=True)[:3]
    top_bet = sorted(nodes, key=lambda n: bet_c.get(n, 0), reverse=True)[:3]

    rows.append({
        "community_id": cid,
        "size": len(nodes),
        "top_degree_nodes": top_deg,
        "top_betweenness_nodes": top_bet
    })

comm_df = pd.DataFrame(rows).sort_values(["size","community_id"], ascending=[False, True]).reset_index(drop=True)
comm_df

"""Nakon primene Louvain algoritma i identifikacije 15 zajednica, izvršena je dodatna analiza centralnosti unutar svake pojedinačne zajednice.

Za svaku zajednicu izračunate su dve mere centralnosti:

- **Degree centrality**
- **Betweenness centrality**

Na osnovu mapiranja `node → community_id`, za svaku zajednicu:

1. identifikovani su svi čvorovi koji joj pripadaju,
2. izdvojena su **tri čvora sa najvećom degree centrality**,
3. izdvojena su **tri čvora sa najvećom betweenness centrality**.

Dobijena tabela sadrži:

- identifikator zajednice (`community_id`),
- veličinu zajednice (`size`),
- čvorove sa najvećom direktnom povezanošću,
- čvorove sa najvećom posredničkom ulogom.

U većim zajednicama (npr. veličine 26, 22 i 21), čvorovi sa visokom degree centrality predstavljaju tipične predstavnike dominantnog sentiment obrasca unutar te grupe. Njihovi aspektni profili su snažno usklađeni sa velikim brojem drugih recenzija u istoj zajednici.

Čvorovi sa visokom betweenness centrality unutar zajednica imaju drugačiju ulogu — oni povezuju različite podgrupe unutar iste zajednice i mogu predstavljati prelazne ili hibridne sentiment profile.

### Vizuelizacija detektovanih zajednica
"""

pos = nx.spring_layout(G, seed=42, k=0.25)

node_to_comm = node_to_comm_louvain

node_colors = [node_to_comm.get(n, -1) for n in G.nodes()]

plt.figure(figsize=(10, 8))

weights = [G[u][v].get("weight", 1.0) for u, v in G.edges()]
edge_widths = [1 + 3*(w - 0.7) for w in weights]
nx.draw_networkx_edges(G, pos, width=edge_widths, alpha=0.25)

nx.draw_networkx_nodes(G, pos, node_size=45, node_color=node_colors)

plt.title("Zajednice u mreži recenzija")
plt.axis("off")
plt.show()

"""Nakon primene Louvain algoritma za detekciju zajednica, izvršena je grafička vizuelizacija mreže recenzija.

U vizuelizaciji:

- Svaki čvor predstavlja jednu recenziju.
- Ivica između dva čvora postoji ukoliko je kosinusna sličnost njihovih aspektnih sentiment profila ≥ 0.7.
- Boja čvora označava pripadnost određenoj zajednici (community_id).
- Debljina ivice proporcionalna je težini veze (cosine similarity).

Za raspored čvorova korišćen je `spring_layout`, koji simulira fizički model opruga:
- čvorovi koji su snažno povezani pozicioniraju se bliže,
- slabo povezani ili izolovani čvorovi udaljeni su od centralne strukture.

Na grafičkom prikazu jasno se uočava:

- Jedna dominantna centralna komponenta sa visokom gustinom veza.
- Nekoliko srednjih klastera unutar centralne strukture.
- Više izolovanih čvorova ili veoma malih zajednica.
- Vizuelno odvojene obojene grupe koje odgovaraju Louvain zajednicama.

Ova struktura je konzistentna sa prethodno izračunatom modularnošću (Q ≈ 0.41), što ukazuje na:

- postojanje jasno diferenciranih obrazaca percepcije kvaliteta usluge,
- ali i prisustvo povezanosti između pojedinih grupa.

Dominantna centralna komponenta predstavlja grupu recenzija sa sličnim i međusobno povezanim sentiment profilima po aspektima (cleanliness, location, staff, comfort, facilities, value_for_money, wifi, food).

Manje zajednice predstavljaju:

- specifične obrasce zadovoljstva,
- ili prelazne/hibridne profile koji nisu u potpunosti uklopljeni u dominantni obrazac.

Izolovani čvorovi (zajednice veličine 1) ukazuju na atipične recenzije čiji aspektni sentiment profil nije dovoljno sličan drugim recenzijama pri zadatom pragu (0.7).

Grafički prikaz potvrđuje da mreža recenzija ima jasnu klastersku strukturu.  
Zajednice detektovane Louvain algoritmom nisu slučajne, već odražavaju realne obrasce sličnosti u percepciji kvaliteta hotela.

### Analiza sentimenta po zajednicama
"""

df_comm = llm_df_f.copy()

comm_sizes = pd.Series(node_to_comm_louvain).value_counts().sort_index()

valid_comms = comm_sizes[comm_sizes >= 2].index.tolist()

print("Ukupno zajednica (Louvain):", len(comm_sizes))
print("Zajednice sa >=2 člana:", len(valid_comms))
print("Singleton zajednice (size=1):", int((comm_sizes == 1).sum()))

df_comm["community_id"] = df_comm.index.map(node_to_comm_louvain)

df_comm_valid = df_comm[df_comm["community_id"].isin(valid_comms)].copy()

sentiment_by_comm = pd.crosstab(df_comm_valid["community_id"], df_comm_valid["overall_sentiment"])

sentiment_by_comm

"""Na osnovu Louvain algoritma detektovano je ukupno **15 zajednica** u mreži recenzija.

Dalja analiza je sprovedena samo nad zajednicama koje imaju **više od jednog člana (size ≥ 2)**, jer zajednice sa jednim čvorom predstavljaju izolovane recenzije i ne mogu se smatrati stabilnim grupama.

- Ukupno zajednica (Louvain): **15**
- Zajednice sa ≥ 2 člana: **6**
- Singleton zajednice (size = 1): **9**

Dakle, samo 6 zajednica predstavljaju stvarne klastere sličnih sentiment profila, dok 9 recenzija imaju atipične ili izdvojene obrasce percepcije.

Analizirana je raspodela `overall_sentiment` vrednosti unutar svake validne zajednice.

Zajednice pokazuju različite obrasce sentimenta:

- **Zajednica 0** je dominantno pozitivna (17 pozitivnih), uz manji broj negativnih i neutralnih ocena.
- **Zajednica 2** ima mešovit profil (10 pozitivnih, 4 neutralna, 4 negativna), što može ukazivati na prelazni ili heterogeni obrazac percepcije.
- **Zajednica 3** je dominantno negativna (8 negativnih), bez neutralnih ocena.
- **Zajednica 4** nema nijednu pozitivnu ocenu, što ukazuje na izrazito nezadovoljstvo ili neutralnost prema oceni u toj grupi.
- **Zajednice 1 i 5** imaju umeren i balansiran raspored sentimenta.

Detektovane zajednice reflektuju **različite obrasce percepcije kvaliteta usluge**.

### Prosečan sentiment po validnim zajednicama
"""

sentiment_numeric = {"negative": -1, "neutral": 0, "positive": 1}

df_comm_valid["sentiment_num"] = df_comm_valid["overall_sentiment"].map(sentiment_numeric)

mean_sentiment_by_comm = (
    df_comm_valid
    .groupby("community_id")["sentiment_num"]
    .mean()
    .sort_values(ascending=False)
)

mean_sentiment_by_comm

"""Radi kvantifikacije dominantnog sentimenta unutar svake zajednice, kategorija `overall_sentiment` mapirana je u numerički oblik:

- negative → -1  
- neutral → 0  
- positive → 1  

- **Zajednice 0 i 1** imaju izraženo pozitivan profil (prosek > 0.5), što znači da unutar tih grupa dominiraju pozitivne recenzije.
- **Zajednice 2 i 5** imaju umeren, ali i dalje pozitivan prosek (~0.33), što ukazuje na mešovitu, ali pretežno pozitivnu percepciju.
- **Zajednice 3 i 4** imaju negativan prosečan sentiment (-0.6), što znači da su to grupe recenzija u kojima dominira nezadovoljstvo.

#### Grafički prikaz prosečnog sentimenta po validnim Louvain zajednicama
"""

community_sentiment = (
    df_comm_valid
    .groupby("community_id")["sentiment_num"]
    .mean()
    .sort_values(ascending=False)
)

comm_sizes_valid = df_comm_valid["community_id"].value_counts().sort_index()

labels = [f"{cid}\n(n={comm_sizes_valid[cid]})" for cid in community_sentiment.index]

plt.figure(figsize=(10, 5))
plt.bar(range(len(community_sentiment)), community_sentiment.values)

plt.axhline(0, color="black", linewidth=1)
plt.title("Prosečan sentiment po validnim Louvain zajednicama (size ≥ 2)")
plt.xlabel("Zajednica")
plt.ylabel("Prosečan sentiment (-1 do 1)")

plt.xticks(range(len(community_sentiment)), labels)
plt.tight_layout()
plt.show()

"""Na grafikonu je prikazan prosečan numerički sentiment po zajednicama detektovanim Louvain algoritmom, pri čemu su iz analize isključene singleton zajednice (size = 1).

Svaka zajednica je označena identifikatorom i veličinom (n), dok je na y-osi prikazana vrednost prosečnog sentimenta u opsegu [-1, 1].

Grafikon pokazuje jasnu polarizaciju mreže:

- Dve najveće zajednice (0 i 1) imaju izraženo pozitivan sentiment profil.
- Zajednice 2 i 5 imaju umeren, ali i dalje pozitivan karakter.
- Zajednice 3 i 4 imaju dominantno negativan sentiment.

## Zaključak

U radu je predstavljen kompletan metodološki okvir transformacije nestrukturiranih tekstualnih recenzija hotela u strukturirani analitički model, korišćenjem velikih jezičkih modela (LLM) i metoda mrežne analize.

Za potrebe istraživanja inicijalno je izdvojen uzorak od **250 recenzija**, nad kojima je planirana LLM analiza. Usled tehničkih ograničenja (API timeout, nevalidni ili nepotpuni odgovori modela), uspešno je strukturirano i validirano **228 recenzija**, dok su preostale recenzije izostavljene iz daljih faza analize. Ovakav pristup je metodološki prihvatljiv, jer su dalji koraci sprovedeni isključivo nad validno obrađenim podacima.

Primena Groq LLM servisa omogućila je automatsku ekstrakciju strukturiranih informacija iz hotelskih recenzija, uključujući:

- opšti sentiment (positive, neutral, negative),
- sentiment po ključnim aspektima usluge (čistoća, lokacija, osoblje, udobnost, sadržaji, vrednost za novac, WiFi, hrana),
- eksplicitno navedene pozitivne i negativne elemente iskustva,
- indikaciju preporuke hotela.

Validacija LLM-ekstrahovanog sentimenta poređenjem sa numeričkom ocenom hotela (transformisanom u kategorije) pokazala je umereno poklapanje. Rezultati potvrđuju da tekstualni sentiment i numerička ocena ne predstavljaju identične dimenzije evaluacije, već komplementarne aspekte korisničkog iskustva.

Transformacijom aspektnih sentimenta u numeričke profile konstruisana je mreža recenzija zasnovana na kosinusnoj sličnosti obrazaca zadovoljstva (threshold = 0.7). Nakon filtriranja recenzija sa nedovoljnim brojem pomenutih aspekata, analizirana je mreža od 108 čvorova.

Louvain algoritam detektovao je 15 zajednica, od kojih 6 imaju više od jednog člana. Dalja analiza sprovedena je samo nad tim validnim zajednicama, dok su singleton čvorovi interpretirani kao atipični ili izolovani obrasci percepcije.

Mrežna analiza je pokazala:

- jasno formiranje pozitivnih i negativnih klastera,
- postojanje prelaznih zajednica sa mešovitim sentiment profilom,
- stabilnu segmentacionu strukturu potvrđenu vrednošću modularnosti (Q ≈ 0.41),
- identifikaciju centralnih recenzija putem degree i betweenness centrality metrika.

Analiza prosečnog sentimenta po zajednicama potvrdila je polarizaciju mreže: najveće zajednice karakteriše dominantno pozitivan sentiment, dok su pojedine zajednice jasno negativno orijentisane. Time je pokazano da detektovane zajednice reflektuju stvarne razlike u percepciji kvaliteta usluge, a ne samo strukturne osobine grafa.

Kombinacijom semantičke analize teksta i mrežnog modelovanja sličnosti, rad demonstrira kako LLM-ekstrahovani podaci mogu biti osnova za napredne kvantitativne i segmentacione analize korisničkog zadovoljstva.

Iako je analiza sprovedena nad podskupu validno obrađenih recenzija, rezultati potvrđuju da integracija LLM modela sa validacionim mehanizmima i metodama mrežne analize predstavlja robustan analitički pristup za ekstrakciju znanja iz nestrukturiranih podataka i podršku donošenju informisanih odluka.
"""